<a href="https://colab.research.google.com/github/Saipraveen1/Perfect_Plan_B/blob/main/Breast_Cancer_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Breast cancer detection with logistc regression

In [ ]:
# import libraries
import numpy as np
import sklearn.datasets

In [ ]:
# getting started wirh dataset
breast_cancer = sklearn.datasets.load_breast_cancer()

In [ ]:
print(breast_cancer)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [ ]:
x = breast_cancer.data
y = breast_cancer.target

In [ ]:
print(x.shape , y.shape)

(569, 30) (569,)


Import data into dataframe



In [ ]:
import pandas as pd

data = pd.DataFrame(breast_cancer.data, columns = breast_cancer.feature_names)

In [ ]:
data['class'] = breast_cancer.target

In [ ]:
data.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [ ]:
data.describe()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
count   569.000000    569.000000  ...      569.000000               569.000000
mean     14.127292     19.289649  ...        0.290076                 0.083946
std       3.524049      4.301036  ...        0.061867                 0.018061
min       6.981000      9.710000  ...        0.156500                 0.055040
25%      11.700000     16.170000  ...        0.250400                 0.071460
50%      13.370000     18.840000  ...        0.282200                 0.080040
75%      15.780000     21.800000  ...        0.317900                 0.092080
max      28.110000     39.280000  ...        0.663800                 0.207500

[8 rows x 30 columns]

In [ ]:
print(data['class'].value_counts())

1    357
0    212
Name: class, dtype: int64


In [ ]:
print(breast_cancer.target_names)

['malignant' 'benign']


In [ ]:
data.groupby('class').mean()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
class                             ...                                         
0        17.462830     21.604906  ...        0.323468                 0.091530
1        12.146524     17.914762  ...        0.270246                 0.079442

[2 rows x 30 columns]

0 - malignat


1 - benign

Train and test split

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y)

In [ ]:
print(y.shape, y_train.shape, y_test.shape)

(569,) (426,) (143,)


In [ ]:
x_train , x_test, y_test, y_test = train_test_split(x,y, test_size = 0.1)

# test_size  -----> to specify the percentage of the test data modified

In [ ]:
print(y.shape, y_train.shape, y_test.shape)

(569,) (426,) (57,)


In [ ]:
print(y.mean(), y_train.mean(), y_test.mean())

0.6274165202108963 0.6384976525821596 0.5614035087719298


In [ ]:
x_test, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, stratify=y) 

# stratify -----> for correct distribution of data as of the original data

In [ ]:
print(y.mean(), y_train.mean(), y_test.mean())

0.6274165202108963 0.626953125 0.631578947368421


In [33]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size= 0.1, random_state=1)

# random state -----> specific split of data. each valuesof random_state splits the data differently

In [34]:
print(x_train.mean(), x_test.mean(), x.mean())

61.8522373819401 62.23631195847954 61.890712339519624


In [36]:
print(x_train)

[[1.881e+01 1.998e+01 1.209e+02 ... 1.294e-01 2.567e-01 5.737e-02]
 [1.366e+01 1.515e+01 8.827e+01 ... 1.054e-01 3.387e-01 9.638e-02]
 [1.026e+01 1.658e+01 6.585e+01 ... 8.333e-02 2.691e-01 9.479e-02]
 ...
 [1.720e+01 2.452e+01 1.142e+02 ... 1.899e-01 3.313e-01 1.339e-01]
 [1.403e+01 2.125e+01 8.979e+01 ... 7.963e-02 2.226e-01 7.617e-02]
 [1.303e+01 1.842e+01 8.261e+01 ... 5.013e-02 1.987e-01 6.169e-02]]


**Logestic** **Regression**

In [39]:
classifier.fit?

In [37]:
# import logistc regresssion from sklearn
from sklearn.linear_model import LogisticRegression

In [38]:
classifier = LogisticRegression() # loading logistic regression model to a variable 'classifier'
classifier.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

**Evaluation model**

In [43]:
# import accuracy_score
from sklearn.metrics import accuracy_score

In [45]:
Prediction_on_training_data = classifier.predict(x_train)
accuracy_on_training_data = accuracy_score(y_train, Prediction_on_training_data)

In [46]:
print('Accuracy on training data: ', accuracy_on_training_data)

Accuracy on training data:  0.943359375


In [47]:
# prediction on test data
Prediction_on_test_data = classifier.predict(x_test)
accuracy_on_test_data = accuracy_score(y_test, Prediction_on_test_data)

In [50]:
print('Accuracy on testing data: ', accuracy_on_test_data)

Accuracy on testing data:  1.0


Detecting wheather the patient has brest cancer in bengin or Maligant


In [71]:
input_Data = (13.54,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.04781,0.1885,0.05766,0.2699,0.7886,2.058,23.56,0.008462,0.0146,0.02387,0.01315,0.0198,0.0023,15.11,19.26,99.7,711.2,0.144,0.1773,0.239,0.1288,0.2977,0.07259)

In [72]:
# change the input_data to numpy_arrray to make predicition
input_data_as_numpy_array = np.asarray(input_Data)
print(input_Data)

# reshape the array as we are predicting the output for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

#prediction
prediction = classifier.predict(input_data_reshaped)
print(prediction) # return a list with the element [0] if malingant; returns a liswitch element[1], if benign.

if (prediction[0] == 0):
    print('The brest cancer is malignant')
else:
  print('The brest cancer is bengin')
    

(13.54, 14.36, 87.46, 566.3, 0.09779, 0.08129, 0.06664, 0.04781, 0.1885, 0.05766, 0.2699, 0.7886, 2.058, 23.56, 0.008462, 0.0146, 0.02387, 0.01315, 0.0198, 0.0023, 15.11, 19.26, 99.7, 711.2, 0.144, 0.1773, 0.239, 0.1288, 0.2977, 0.07259)
[1]
The brest cancer is bengin
